<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\networkermenu.android.networker" />
    <None Remove="Resources\networkermenu.networker" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\networkermenu.android.networker" />
    <EmbeddedResource Include="Resources\networkermenu.networker" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/net8/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BoneLib">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/Mods/BoneLib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/net8/Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSLZ.Algorithms">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSLZ.Algorithms.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSLZ.Algorithms.Unity">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSLZ.Algorithms.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSLZ.Marrow">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSLZ.Marrow.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSLZ.Marrow.VoidLogic.Core">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSLZ.Marrow.VoidLogic.Core.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSLZ.Marrow.VoidLogic.Engine">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSLZ.Marrow.VoidLogic.Engine.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSLZ.ModIO">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSLZ.ModIO.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSLZ.Serialize">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSLZ.Serialize.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSystem.Core.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppUniTask">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Il2CppUniTask.dll</HintPath>
    </Reference>
    <Reference Include="LabFusion">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/Mods/LabFusion.dll</HintPath>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/net8/MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/net8/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Animation.Rigging">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Animation.Rigging.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Barracuda">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Barracuda.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Barracuda.BurstBLAS">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Barracuda.BurstBLAS.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst.Unsafe">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Burst.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ML-Agents">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.ML-Agents.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ML-Agents.CommunicatorObjects">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.ML-Agents.CommunicatorObjects.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.ProBuilder.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.KdTree">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.ProBuilder.KdTree.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.Poly2Tri">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.ProBuilder.Poly2Tri.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Profiling.Core">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Profiling.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.StressLevelZero.VRS">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.RenderPipelines.Universal.StressLevelZero.VRS.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Splines">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Splines.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Splines.Examples">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Splines.Examples.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.Timeline.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.ARFoundation">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.ARFoundation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.ARSubsystems">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.ARSubsystems.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.CoreUtils">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.CoreUtils.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.Interaction.Toolkit">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.Interaction.Toolkit.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.Management">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.Management.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.MockHMD">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.MockHMD.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.Oculus">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.Oculus.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.OpenXR.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.ConformanceAutomation">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.OpenXR.Features.ConformanceAutomation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.MetaQuestSupport">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.OpenXR.Features.MetaQuestSupport.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.MockRuntime">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.OpenXR.Features.MockRuntime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.OculusQuestSupport">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.OpenXR.Features.OculusQuestSupport.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.RuntimeDebugger">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/Unity.XR.OpenXR.Features.RuntimeDebugger.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AccessibilityModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.AccessibilityModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.AndroidJNIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ARModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ARModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ClothModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterInputModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ClusterInputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterRendererModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ClusterRendererModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.CrashReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.DirectorModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DSPGraphModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.DSPGraphModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.GameCenterModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GIModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.GIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.GridModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.HotReloadModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.HotReloadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.InputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.LocalizationModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.LocalizationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.NVIDIAModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.NVIDIAModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PerformanceReportingModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.PerformanceReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ProfilerModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ProfilerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.SharedInternalsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpatialTracking">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.SpatialTracking.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.SpriteMaskModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteShapeModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.SpriteShapeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.StreamingModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.StreamingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubstanceModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.SubstanceModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.SubsystemsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TLSModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.TLSModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsNativeModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UIElementsNativeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UmbraModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UmbraModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UNETModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UNETModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityConnectModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityConnectModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityCurlModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityCurlModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityTestProtocolModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityTestProtocolModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.VehiclesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VFXModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.VFXModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VirtualTexturingModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.VirtualTexturingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>/home/zoey/com.StressLevelZero.BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.XRModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Copy SourceFiles="$(TargetPath)" DestinationFolder="/home/zoey/com.StressLevelZero.BONELAB/Mods" />
    </Target>
</Project>
